{% set name = "protovalidate-python" %}
{% set pypi_name = "protovalidate" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/protovalidate-{{ version }}.tar.gz
  sha256: f2fce76be2afc91f1c2f57b0d1bba26a1681cf687ba387a3a4bea6a69e13a805

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.12,<2.0
  run:
    - python
    - protobuf-py >=0.2.0

test:
  imports:
    - protovalidate
  source_files:
    - test/
  requires:
    - pip
    - pytest >=8.4.1
  commands:
    - pip check
    - pytest -v test/

about:
  home: https://protovalidate.com
  summary: Protocol Buffer Validation for Python.
  description: |
    Protovalidate is the semantic validation library for Protobuf.
    It provides standard annotations to validate common rules on messages
    and fields, as well as the ability to use CEL to write custom rules.
    It's the next generation of protoc-gen-validate.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/bufbuild/protovalidate-python
  doc_url: https://protovalidate.com/about
