{% set name = "protovalidate-python" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bufbuild/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4642080af57f33bc84fa47c59511d74ab0be2826bc4452f5d381332f567faf87
  patches:
    - patches/0001-Include-gen-buf-to-the-build.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - protobuf >=6.31.0  # [py>=314]
    - cel-python >=0.5
    - google-re2 >=1.1.20250722  # [py>=313]
    - google-re2 >=1.1  # [py==312]
    - google-re2 >=1  # [py<312]

test:
  imports:
    - protovalidate
  source_files:
    - test/
    - gen/
  requires:
    - pip
    - pytest >=8.4.1
  commands:
    - pip check
    - pytest -v test/

about:
  home: https://protovalidate.com
  summary: Protocol Buffer Validation for Python.
  description: |
    Protovalidate is the semantic validation library for Protobuf.
    It provides standard annotations to validate common rules on messages
    and fields, as well as the ability to use CEL to write custom rules.
    It's the next generation of protoc-gen-validate.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/bufbuild/protovalidate-python
  doc_url: https://protovalidate.com/about
